enableStrictSsl: false

yarnPath: .yarn/releases/yarn-3.6.3.cjs

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
