name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
      - '**/.eslintrc'
      - '**/.prettierrc'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install
        run: |
          yarn install --immutable --immutable-cache

      - name: Build 🔧
        run: yarn build

      - name: Add .nojekyll
        run: touch dist/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist
