name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
      - '**/.eslintrc'
      - '**/.prettierrc'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache ./public
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/public
          key: ${{ runner.os }}-gatsby-public-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gatsby-public-

      - name: Cache ./.cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.cache
          key: ${{ runner.os }}-gatsby-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gatsby-cache-

      - name: Install
        run: |
          cd ${{ github.workspace }}/plugins/gatsby-remark-breaks
          yarn install
          cd ${{ github.workspace }}/plugins/gatsby-remark-embed
          yarn install
          cd ${{ github.workspace }}
          yarn install

      - name: Build 🔧
        run: |
          yarn clean
          yarn build

      - name: Add .nojekyll
        run: touch public/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
