name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
      - '**/.eslintrc'
      - '**/.prettierrc'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Restore cached images
        id: cache-images-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules/.astro/assets
          key: ${{ runner.os }}-images

      - name: Build 🔧
        run: pnpm build

      - name: Save images
        id: cache-images-save
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules/.astro/assets
          key: ${{ steps.cache-images-restore.outputs.cache-primary-key }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
